### ISSUE TITLE
Implement overlay flow

### ISSUE THREAD

**Issue by pocmo** [pocmo/WebCards#12]
- ~~if open > single pressing on the green circle will open the app~~
- ~~if open > dragging the green circle to the right will collapse the overlay~~
- ~~if close > dragging the green circle will allow the user to place it somewhere else along the right side, or dismiss the overlay entirely by dragging it to the bottom right~~
- ~~if close> single pressing on the green semi-circle/tab looking thing will open the overlay~~

**Comment by antlam** [comment]
For now, the basic interactions look as follows:
When collapsed:
- Single-press on the "tab UI" will expand the tray
- Dragging the "tab UI" lets the user move the UI out of their way (or drag it to the bottom to close it altogether)

When expanded:
- Single-press on the "button" to open the App
- Dragging the "button" to the right will collapse the tray again

**Comment by antlam** [comment]
![uxflow1](https://cloud.githubusercontent.com/assets/1994820/16501863/6fb7704a-3ec0-11e6-8c63-5625c50dce89.png)
From previous conversations

**Comment by pocmo** [comment]
All interactions are implemented now. The actual look & feel will be implemented in #4.
